apps/pls/protected/controllers/HelpController.php
<?php

/**
 * @class      HelpController
 *
 * This is the controller that contains the /help actions.
 *
 * @author     Developer
 * @copyright  PLS 3rd Learning, Inc. All rights reserved.
 */
class HelpController extends Controller {

	/**
	 * Specifies the action filters.
	 *
	 * @return array action filters
	 */
	public function filters() {
		return [
			'accessControl', // perform access control for CRUD operations
		];
	}

	/**
	 * Specifies the access control rules.
	 *
	 * @return array access control rules
	 */
	public function accessRules() {
		return [
			['allow',  // allow all users to access specified actions.
				'actions' => ['index', 'contact', 'updates'],
				'users'   => ['*'],
			],
			['allow', // allow authenticated users to access all actions
				'users' => ['@'],
			],
			['deny',  // deny all users
				'users' => ['*'],
			],
		];
	}

	/**
	 * Declares class-based actions.
	 *
	 * @return array[]
	 */
	public function actions() {
		return [
			// captcha action renders the CAPTCHA image displayed on the contact page
			'captcha' => [
				'class'     => 'CCaptchaAction',
				'backColor' => 0xFFFFFF,
			],
		];
	}

	/**
	 * Renders the contact page and handles form submission.
	 *
	 * @return void
	 */
	public function actionContact() {
		$model = new ContactForm();
		if (!empty(Yii::app()->request->getPost('ContactForm'))) {
			$model->attributes = Yii::app()->request->getPost('ContactForm');
			if ($model->validate()) {
				$headers = [
					'From'     => $model->email,
					'Reply-To' => $model->email,
				];
				mail(Yii::app()->params['adminEmail'], $model->subject, $model->body, $headers);
				Yii::app()->user->setFlash('contact', 'Thank you for contacting us. We will respond to you as soon as possible.');
				$this->refresh();
			}
		}
		$this->render('contact', ['model' => $model]);
	}

	/**
	 * Renders the help videos page.
	 *
	 * @return void
	 */
	public function actionVideos() {
		// Not implemented
	}

	/**
	 * Renders the user manuals page.
	 *
	 * @return void
	 */
	public function actionManuals() {
		// Not implemented
	}

	/**
	 * Renders the latest updates page based on an RSS feed.
	 *
	 * @return void
	 * @throws FeedException
	 */
	public function actionUpdates() {
		$blogService = new BlogService();
		$feed = $blogService->getUpdates();
		$items = [];
		if (!empty($feed)) {
			foreach ($feed->item as $item) {

				if(count($items) >= 5)
					break;
				
					$items[] = new Blog($item);
			}
		}
		$this->render('updates', ['items' => $items]);
	}
}

apps/pls/protected/views/layouts/column1.php
<?php
/**
 * @var Controller $this
 * @var string     $content
 */
?>
<?php $this->beginContent('/layouts/main'); ?>
	<div class="container">
		<div id="content">
			<?= $content ?>
		</div>
	</div>
<?php $this->endContent(); ?>

apps/pls/protected/views/layouts/main.php
<?php
/**
 * @var Controller $this
 * @var string     $content
 */
?>

<!doctype html>
<html lang="en">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/main.css"/>
<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/form.css"/>

<link href="<?php echo Yii::app()->request->baseUrl; ?>/css/bootstrap.min.css" rel="stylesheet"/>
<link href="https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.min.css" rel="stylesheet"/>
<script src="https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.min.js"></script>
<script src="https://code.jquery.com/jquery-3.6.1.slim.min.js"></script>

<title><?php echo CHtml::encode($this->pageTitle); ?></title>
</head>

<body>
<main class="container" id="page">

	<header class="d-flex flex-wrap justify-content-left border-bottom" id="header">
		<img id="logo" class="ml-2" src="<?php echo Yii::app()->request->baseUrl; ?>/images/logo.png" alt="Logo"/>
	</header>

	<nav class="navbar navbar-expand-lg bg-light">
		<a class="navbar-brand" href="#"><?= Yii::t('pls', 'Sample Application') ?></a>
		<div class="navbar-collapse">
			<ul class="navbar-nav nav nav-pills">
				<?php
				if (Yii::app()->user->isGuest) {
					?>
					<li class="nav-item"><a href="/site/login" class="nav-link"><?= Yii::t('pls', 'Login') ?></a></li>
					<?php
				}
				else {
					?>
					<li class="nav-item"><a href="/site/logout" class="nav-link"><?= Yii::t('pls', 'Logout') ?></a></li>
					<?php
				}
				?>
				<li class="nav-item"><a href="/site/about" class="nav-link"><?= Yii::t('pls', 'About') ?></a></li>
				<li class="nav-item"><a href="/help/updates" class="nav-link"><?= Yii::t('pls', 'Latest Updates') ?></a>
				</li>
				<li class="nav-item"><a href="/help/contact" class="nav-link"><?= Yii::t('pls', 'Contact') ?></a></li>
			</ul>
		</div>
	</nav>

	<main>
		<?php
		$this->widget('zii.widgets.CBreadcrumbs', [
			'links' => $this->breadcrumbs,
		]);
		?>
		<div class="row my-2">
			<?= $content ?>
		</div>
	</main>

	<footer>
		<?= Yii::app()->params['copyrightInfo'] ?>
	</footer>

</main>
</body>
</html>